export const CREATE_TASK_TIMER_REQUEST = 'CREATE_TASK_TIMER_REQUEST';
export const CREATE_TASK_TIMER_SUCCESS = 'CREATE_TASK_TIMER_SUCCESS';
export const CREATE_TASK_TIMER_FAILURE = 'CREATE_TASK_TIMER_FAILURE';


// Update 
export const UPDATE_TASK_TIMER_REQUEST = 'UPDATE_TASK_TIMER_REQUEST';
export const GET_TASK_TIMER_SUCCESS = 'GET_TASK_TIMER_SUCCESS';
export const UPDATE_TASK_TIMER_SUCCESS = 'UPDATE_TASK_TIMER_SUCCESS';
export const TASK_TIMER_ERROR = 'TASK_TIMER_ERROR';
